name: AutoSign

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rewrite:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4

      # check-out the signutils repo
      - name: Check out ACESignSupport
        uses: actions/checkout@v4
        with:
          repository: stijn-volckaert/ACESignSupport
          token: ${{ secrets.SIGNSUPPORTTOKEN }}
          ref: main
          path: ACESignSupport

      - run: chmod u+x ACESignSupport/ACESign-CryptoPP

      - run: chmod u+x ACESignSupport/ACESign-OpenSSL

      - name: Rewrite timestamp and sign filelist
        run: /usr/bin/ruby ACESignSupport/signutils.rb

      - run: rm -rf ACESignSupport

      # Commit updated file list back to the repo
      - uses: stefanzweifel/git-auto-commit-action@v5
